Try to fix github action

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -58,7 +58,7 @@ jobs:
       - name: Run Migration and Load fixtures
         run: |
           composer require --dev symfony/orm-pack
-          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console doctrine:schema:drop --full-database --force || echo "Cannot drop the schema"
           php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
           php bin/console doctrine:fixtures:load --no-interaction || echo "Loading fixtures failed"
         env:
@@ -69,3 +69,5 @@ jobs:
 
       - name: Run tests
         run: simple-phpunit --coverage-text
+        env:
+          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
